### ISSUE TITLE
crash in browser

### ISSUE THREAD

**Issue by gucio321** [neonKnights/ReactionEditor#1]
editor crashes after attempting to add arrow

**Comment by gucio321** [comment]
rebuilding...

**Comment by gucio321** [comment]
```console
Uncaught RuntimeError: float unrepresentable in integer range
    at WebGL.wasm:0xa26def
    at WebGL.wasm:0xa263e1
    at WebGL.wasm:0x66059e
    at WebGL.wasm:0xa3e152
    at Object.dynCall_iiiii (WebGL.framework.js:2:421553)
    at invoke_iiiii (WebGL.framework.js:2:306086)
    at WebGL.wasm:0x9e248e
    at WebGL.wasm:0x9ca120
    at WebGL.wasm:0x17c9f5
    at WebGL.wasm:0x17c6c5
    at WebGL.wasm:0x2e2c22
    at WebGL.wasm:0x2e1b43
    at WebGL.wasm:0x46d7fc
    at WebGL.wasm:0x51cbc4
    at WebGL.wasm:0x51cd5a
    at WebGL.wasm:0x525860
    at WebGL.wasm:0x735846
    at WebGL.wasm:0xa28690
    at WebGL.wasm:0x63d0af
    at WebGL.wasm:0x6f1472
    at WebGL.wasm:0x78ba77
    at WebGL.wasm:0xa3e483
    at Object.dynCall_viiii (WebGL.framework.js:2:434421)
    at invoke_viiii (WebGL.framework.js:2:329875)
    at WebGL.wasm:0x8af293
    at WebGL.wasm:0x6e44f0
    at WebGL.wasm:0x9624d5
    at WebGL.wasm:0x96397b
    at WebGL.wasm:0x963235
    at WebGL.wasm:0x962b64
    at WebGL.wasm:0x96284a
    at WebGL.wasm:0x609924
    at WebGL.wasm:0x6f0b43
    at WebGL.wasm:0x66059e
    at WebGL.wasm:0xa3e152
    at Object.dynCall_iiiii (WebGL.framework.js:2:421553)
    at invoke_iiiii (WebGL.framework.js:2:306086)
    at WebGL.wasm:0x9e248e
    at WebGL.wasm:0x9ca120
    at WebGL.wasm:0x17c9f5
    at WebGL.wasm:0x17c6c5
    at WebGL.wasm:0x3a2580
    at WebGL.wasm:0x3a109a
    at WebGL.wasm:0x4d143a
    at WebGL.wasm:0x4d1154
    at WebGL.wasm:0x3d0fc9
    at WebGL.wasm:0x3ab743
    at WebGL.wasm:0x3ab758
    at WebGL.wasm:0x3ab2de
    at WebGL.wasm:0x3a96b9
```

**Comment by gucio321** [comment]
I'll try to reproduce in unity editor...

**Comment by gucio321** [comment]
okey, reproducable in unity, fixing...
